#!/bin/sh

if which podman>/dev/null; 
then 
PROGRAM=podman; 
else 
PROGRAM=docker; 
fi

$PROGRAM run -it --rm \
    --volume $PWD:/project \
    --env RUSTFLAGS='-C target-cpu=x86-64-v3' \
    docker.io/library/rust:1-bullseye sh -c \
    "apt-get -y update ;\
    apt-get -y install mingw-w64 ;\
    rustup target add x86_64-pc-windows-gnu ;\
    cargo build --manifest-path /project/Cargo.toml --release --target x86_64-pc-windows-gnu"
