#!/bin/sh

if which podman>/dev/null; 
then 
PROGRAM=podman; 
else 
PROGRAM=docker; 
fi

$PROGRAM run -it --rm \
    --volume $PWD:/project \
    --env RUSTFLAGS='-C target-cpu=x86-64-v3' \
    docker.io/library/ubuntu:18.04 sh -c \
    "apt-get -y update ;\
    apt-get -y install wget build-essential lld ;\
    wget --no-verbose https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init ;\
    chmod +x rustup-init ;\
    ./rustup-init -y ;\
    /root/.cargo/bin/cargo build --manifest-path /project/Cargo.toml --release"
