[package]
name = "addin-tech-log-parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tech-log-parser = {path = "../parser"}
addin1c = "0.4"
serde = "1.0"
serde_json = "1.0"
chrono = { version = "*", features = ["serde"] }
